name: report
version: 0.1.0.0
synopsis: An implementation of HDTP in Haskell
description: See report.pdf
maintainer: M. Petrowitch, X. Ripoll, R. Tosswill
category: Logic

ghc-options: -Wall

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: lib

tests:
  simpletests:
    main: Tests.lhs
    source-dirs: test
    dependencies:
      - report
      - hspec
